appinfo/app.php, js/app.js
Move development in to the master.
=> Extend sharedialog

appinfo/app.php, appinfo/info.xml, controller/settingscontroller.php, js/guests.js, lib/groupbackend.php, settings/admin.php, templates/settings/admin.php
- Removed quota and contacts options
- Reworked ui to reflect virtual guest group
- Settings use modern settings registrationb method
=> #23 Settings rework

lib/mail.php
The guest app mailer used to retreive the users email address directly from oc_preferences. With the changes to account table this doesn`t work anymore. 
This pr modifies the code to use IUserManager instead of accessing the db directly.
=> Retreive email trough interface instead of directly from db

js/app.js
add more allowed characters in username generator
=> Fix faulty API endpoint

lib/mail.php
=> Use permalink/direct link in the email #54

js/app.js
=> Inconsistent default permission 

tests/integration/guests_features/Guests.feature
add test scenario guest user can upload a file in the folder shared
=> add test guest user can upload file in a folder

tests/integration/guests_features/Guests.feature
Add integration test mail already used for other guest user
=> Mail already used for other guest user

tests/integration/guests_features/Guests.feature
Add integration test for checking guest user deletion.
**Note:** Maybe in the sort term this test should be modified in order to take into account this issue: https://github.com/owncloud/guests/issues/34
=> check guest user is deleted from guests_app group

tests/integration/guests_features/Guests.feature
Integration test for upload and reshare
=> uploads and reshares with a guest

settings/admin.php
this allows proper display in settings and interaction with e2eeshare app
=> fix settings section

appinfo/info.xml
@hurradieweltgehtunter 
We might want to embed the video?
=> Add summary and documentation, change description and author

Makefile, README.md, tests/integration/run.sh
Here is a Makefile, as requested in #24 
I tried to get the appstore/signing procedure into the Makefile as well, but since this is my first for ownCloud, please be considerate with me.
Does it comply with the requirements?
=> add Makefile, adjust README/fix path in integration tests

appinfo/info.xml
Version in info.xml should be the same as the one in the changelog.md file
=> Bump version in info.xml

CHANGELOG.md
I was using the _GitHub Changelog Generator_ and stripped all _not notable_ entries, for older releases just adjusted the .md syntax
=> adapt CHANGELOG.md for #140

CHANGELOG.md
links now go to compare, not to tree
=> CHANGELOG.md: fix version links

.gitignore, CHANGELOG.md, Makefile, appinfo/app.php, appinfo/info.xml, appinfo/routes.php, controller/registercontroller.php, controller/settingscontroller.php, controller/userscontroller.php, js/guests.js, js/navigation.js, lib/appwhitelist.php, lib/groupbackend.php, lib/hooks.php, lib/mail.php, settings/admin.php, templates/form.password.php, templates/mail/altinvite.php, templates/mail/invite.php, templates/settings/admin.php, tests/integration/features/bootstrap/GuestsContext.php
- better Makefile
- added .gitignore
Open tasks for using default Makefile
- vue -> production dependency
- rest -> dev dependency
=> Release Changes for master

tests/integration/guests_features/Guests.feature
which happened in core recently.
=> Remove capitalization in integration test steps

tests/integration/features/bootstrap/GuestsContext.php
There were some changes added in core and this app requires to be adapted to them.
owncloud/core#28989
Backport here owncloud/core#29012
=> Adaptation to Phil's refactor

templates/form.password.php
The duplicate id was causing display errors, fixes #159
=> remove duplicate id

controller/userscontroller.php
fixes https://github.com/owncloud/enterprise/issues/2267
=> Add event driven password generation

CHANGELOG.md
=> Changelog for v0.5.0

appinfo/info.xml
=> bump version and update php min version

tests/integration/features/bootstrap/GuestsContext.php, tests/integration/guests_features/Guests.feature
Refactoring to make the integration tests here compatible with the new refactoring of core integration/API tests in https://github.com/owncloud/core/pull/30413
=> Integration test refactor for core changes 2018-02

tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/GuestsContext.php, tests/acceptance/run.sh
to match core changes in https://github.com/owncloud/core/pull/30943
=> Remove /ocs/ from end of acceptance tests baseUrl

.drone.yml
guests app should behave the same when using objectstore
=> test on objectstore

lib/appwhitelist.php
=> add password_policy and oauth2 to default whitelist

.drone.yml
The test bucket needs to be created using an occ command
see owncloud/core#32099
=> add create-bucket command

tests/acceptance/features/apiGuests/guests.feature, tests/acceptance/features/bootstrap/GuestsContext.php
like we do in core these days.
=> Use abstract admin username in test scenarios

appinfo/app.php, appinfo/info.xml, lib/AppInfo/Application.php, lib/hooks.php, lib/mail.php
Closes #235 
Ref https://github.com/owncloud/core/pull/26608
=> Do not depend on legacy sharing API methods

README.md
There are more apps added in the guests whitelist due to PR: https://github.com/owncloud/guests/pull/227
=> update readme file that contains the white list

CHANGELOG.md, appinfo/info.xml
update 0.6.0 version max-version to 11.0.0.0 for switching to Semver.
=> update 0.6.0 version max-version to 11.0.0.0

appinfo/info.xml
Bump up to max-version 11.0.0.0 again so that CI will run against core master.
=> Bump core max-version v11.0.0.0

appinfo/app.php, controller/registercontroller.php, controller/userscontroller.php, css/personal.css, lib/AppInfo/Application.php, tests/acceptance/features/apiGuests/guests.feature
Tasks from https://github.com/owncloud/guests/issues/114#issuecomment-399955795
Fixes #114
=> Guest users shouldn't be able to create other guest users #114

tests/acceptance/features/apiGuests/guests.feature
=> Adjust user creation test steps

tests/acceptance/features/apiGuests/guests.feature, tests/acceptance/features/bootstrap/GuestsContext.php
Refactor acceptance tests to remove explicit mention of "admin".
#281 
Local acceptance test run
=> Refactor acceptance test 'the administrator' steps

tests/acceptance/features/apiGuests/guests.feature, tests/acceptance/features/bootstrap/GuestsContext.php
Refactor acceptance tests to remove explicit mention of "admin".
#281 
Local acceptance test run
=> Refactor acceptance test 'the administrator'

tests/acceptance/features/apiGuests/guests.feature, tests/acceptance/features/bootstrap/GuestsContext.php
more test cases for chunked uploads, incl. async upload
fixes #216
fixes #278 
more tests = more better
=> more chunking upload tests

tests/acceptance/features/bootstrap/GuestsContext.php
function was moved to helper in https://github.com/owncloud/core/pull/33854
=> move uploadWithAllMechanisms to helper

README.md
=> Add build status for drone

.drone.yml, Makefile, appinfo/info.xml, lib/AppInfo/Application.php, lib/GroupBackend.php, tests/phpunit.xml, tests/unit/GroupBackendTest.php
Fix endless activity loop when sharing with "guest_app" group and add unit tests.
https://github.com/owncloud/enterprise/issues/3041
Discussion with @DeepDiver1975 . GroupInterface needs to be implemented correctly.
He requested to add unit tests.
- Manually
- Unit Tests
=> Fix share with guest_app endless loop, add unit tests

Makefile, phpunit.xml
- move ``phpunit.xml`` to the top folder
- adjust ``Makefile`` ...
In other apps we have ``phpunit.xml`` in the top folder, so do the same here in ``guests`` app.
CI
=> Move phpunit to root

tests/acceptance/features/bootstrap/GuestsContext.php
Use `HttpRequestHelper::sendRequest` instead of `GuzzleHttp\Client` for sending request
#291
=> Use http request helper instead of guzzle client for acceptance test

tests/acceptance/features/bootstrap/GuestsContext.php
makes it possible to set a password when registering a user
https://github.com/owncloud/password_policy/issues/175
=> register user with password

Makefile, phpcs.xml, tests/acceptance/features/bootstrap/GuestsContext.php, tests/acceptance/features/bootstrap/WebUIGuestsContext.php, vendor-bin/php_codesniffer/composer.json
Like was merged in core in https://github.com/owncloud/core/pull/34191
So that we know if we break our own rules for acceptance test code style.
=> Add php codesniffer

tests/acceptance/features/bootstrap/GuestsContext.php
core issue https://github.com/owncloud/core/issues/34367
=> Use core getPathFromCoreToAppAcceptanceTests method

CHANGELOG.md, Makefile, appinfo/info.xml
Closes https://github.com/owncloud/guests/issues/289
=> Release 0.8.0

composer.lock, phpunit.xml, tests/acceptance/features/bootstrap/WebUIGuestsContext.php, tests/unit/GroupBackendTest.php, tests/unit/HooksTest.php
1) Adjust PHPUnit Framework namespace for PHPUnit6
2) phpunit enable failOnRisky
3) Updating bamarni/composer-bin-plugin (v1.2.0 => v1.3.0)
=> Phpunit 5 6

js/guestshare.js
Convert shareWith value to lower case, when
passing attributes to create guest share.
Signed-off-by: Sujith H <sharidasan@owncloud.com>
Convert the `shareWith` attributes passed to create guest share to lower case. Because this value is used directly by the share API and hence inconsistency arises because of the same. In the guests app we convert the uid ( which is the email id ) to lower case while creating guest user. This is a pure js change.
The `shareWith` attribute passed while creating guest share is not converted to lower case. This causes inconsistency in accessing the share. This is a pure front end change.
- Create guest user with upper case and lower case
- Access the link to set the password for the guest user from the email
=> Convert shareWith value to lower case

.drone.yml, tests/acceptance/config/behat.yml, tests/acceptance/features/bootstrap/WebUIGuestsContext.php, tests/acceptance/features/bootstrap/bootstrap.php, tests/acceptance/features/webUIGuests/guests.feature
Acceptance test for creating guest user form webui
=> acceptance test for creating guest user from webui

tests/acceptance/features/bootstrap/GuestsContext.php, tests/acceptance/features/bootstrap/WebUIGuestsContext.php, tests/acceptance/features/lib/SetPasswordPage.php, tests/acceptance/features/webUIGuests/guests.feature
acceptance test for creating guest with email containing capital letter
=> acceptance test for creating guest with email containing capital letter

.drone.yml, tests/acceptance/features/webUIGuests/guests.feature
Currently we only run app tests against stable10 to make sure they will be compatible with the future OC core platform release.
This test guarantee that the ```guests``` app runs correctly against the last released core version.
Part of https://github.com/owncloud/QA/issues/611
=> guest app test against latest release tarball

.drone.yml
#339 added running acceptance tests against latest stable release of core. But in test runner make command was used to build which takes a lot of time. So only install required dependencies to run the tests.
Related Issue https://github.com/owncloud/QA/issues/611
=> Only install required dependencies in test runner in drone

CHANGELOG.md, appinfo/info.xml
Add relevant Changelog items and bump version to 0.8.2
=> add changelog and bump version to 0.8.2

CHANGELOG.md, appinfo/info.xml
Reverts owncloud/guests#345 Rewording needed for the already PR merged
=> Adjust changelog for 0.8.2

.drone.yml
This avoids testing on 10.2.1 on the release branch
Have a 💚 release branch
=> fix failing jobs for current release cycle

.drone.yml
Issue #358 
10.3.0alpha is available, so use that for now. (later beta/RC/release will come...)
=> Test against 10.3.0alpha

.drone.starlark, .drone.yml, phpunit.xml, tests/acceptance/features/webUIGuests/guests.feature
1) initial drone starlark
2) use the usual ouput file name for phpunit coverage reports, so that the "standard" starlark script works
3) run acceptance tests against `10.3.0alpha2` tarball rather than "latest" because guests app now requires 10.3.0 and does not work properly with core 10.2.1
4) `skipOnFirefox` test that has trouble (see existing issue #332 )
=> Initial drone starlark

.drone.starlark, .drone.yml
To run on both `scality` and `ceph`
=> Adjust objectstore tests

.drone.starlark, .drone.yml, composer.json, composer.lock, phpunit.xml, tests/unit/GroupBackendTest.php, tests/unit/HooksTest.php, vendor-bin/behat/composer.json
Similar to https://github.com/owncloud/configreport/pull/121
=> Adjust tests

.drone.starlark, .drone.yml, vendor-bin/owncloud-codestyle/composer.json
like done in core https://github.com/owncloud/core/pull/36580
and apply latest drone starlark code changes
Note: there were no changes to PHP code needed for this app to pass code-style 2.0.0
=> Coding standard 2.0.0

tests/acceptance/features/bootstrap/WebUIGuestsContext.php, tests/acceptance/features/webUIGuests/guests.feature
Add acceptance tests to assert guest user has permission denied to create or upload files
- Fixes https://github.com/owncloud/core/issues/36712
=> Test to assert guest user has permission denied to create or upload files

tests/acceptance/features/apiGuests/guests.feature, tests/acceptance/features/bootstrap/GuestsContext.php, tests/acceptance/features/bootstrap/WebUIGuestsContext.php, tests/acceptance/features/lib/SetPasswordPage.php, tests/acceptance/features/webUIGuests/guests.feature
1) format the feature files to fix the indent mentioned in https://github.com/owncloud/guests/pull/386#discussion_r366158428
2) make code changes suggested by PHPstorm code inspection
CI
=> Acceptance test code inspection changes

vendor-bin/behat/composer.json
Needed because of owncloud/core#36999
=> [Tests-Only] Update guzzle for testing to 6.5

CHANGELOG.md, appinfo/info.xml
Closes https://github.com/owncloud/guests/issues/397
=> Merge back Release 0.9.0

phpstan.neon, vendor-bin/phpstan/composer.json
Related - owncloud/QA#642
Update phpstan to 0.12
=> Update phpstan to 0.12

.drone.star, lib/Controller/RegisterController.php, lib/Controller/UsersController.php, lib/Mail.php, vendor-bin/phan/composer.json
With this pr:
- Updated phan to v2.7
- Run phan in CI
- (Suppress+Fix) failing phan issues
Part of https://github.com/owncloud/QA/issues/643
Run phan in CI without any issues!
:robot:
=> [Tests-Only] Bump phan 2.7 & Run phan in CI

tests/acceptance/features/apiGuests/guests.feature, tests/acceptance/features/webUIGuests/guests.feature
Similar to what was done in core recently.
=> Use realistic usernames

tests/acceptance/features/webUIGuests/guests.feature
Some app tests are failing due to the changes made by PR https://github.com/owncloud/core/pull/37332/ This PR fixes test failing in `guests` app
- Fixes https://github.com/owncloud/guests/issues/416
=> [Tests-only] Fix failing tests after core changes

.drone.star, lib/Controller/SettingsController.php, lib/Controller/UsersController.php, lib/Mail.php, phpstan.neon
Related - owncloud/QA#642
Update phpstan to 0.12
=> [Tests-Only] Update phpstan to latest version

tests/acceptance/features/apiGuests/guests.feature, tests/acceptance/features/webUIGuests/guests.feature
like was done in core last week.
Fixes CI
=> [tests-only] Specify skeleton in tests

CHANGELOG.md, appinfo/info.xml
change release 0.9.1 to master because of release
=> Release 0.9.1

lib/Mail.php
related: https://github.com/owncloud/enterprise/issues/4516#issuecomment-832667221
=> add error log for mailing

lib/AppInfo/Application.php, lib/Capabilities.php, lib/Controller/UsersController.php
1. Added guests app to capabilities:
```
"guests_v1" : {
"enabled" : true
}
```
2. return `displayname`, `userid`, `displayname` in index.php/apps/guests/users PUT reponse 
```
{"userid":"test@web.de","displayname":"test@web.de","email":"test@web.de","message":"User successfully created"}
```
=> Add capabilities extend create response

tests/acceptance/features/bootstrap/GuestsContext.php
core PR https://github.com/owncloud/core/pull/39036 changed the parameters of various test helper functions. Adjust the calls.
=> [tests-only] [full-ci] Adjust calls to test helper functions

lib/AppWhitelist.php
add oco_selfservice to default whitelist
=> Add oco_selfservice to default whitelist

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
Closes: #454 
FYI: GitHub found 21 vulnerabilities on owncloud/guests's default branch (1 critical, 11 high, 5 moderate, 4 low) - https://github.com/owncloud/guests/security/dependabot
=> Merge back Release 0.9.2

.drone.star, Makefile
to check that the JavaScript changes work here.
Part of issue https://github.com/owncloud/QA/issues/687
=> [tests-only] Update .drone.star from activity app

CHANGELOG.md, js/app.js, templates/form.password.php
Adapts to new login form design: https://github.com/owncloud/core/pull/38506
Before:
After:
=> changes to comply with new login form design

CHANGELOG.md, appinfo/info.xml
merge back to master after release.
=> Release 0.9.3

.drone.star, phpunit.xml, sonar-project.properties, vendor-bin/behat/composer.json
* Skip coverage for PHP 7.3
* Update `phpunit.xml` to match the new structure for PHPUnit 9.5
=> [tests-only] Ensure compatibility with PHPUnit v9.5

.drone.star, vendor-bin/phan/composer.json
1) Update to latest .drone.star code
2) Bump PHP phan to major version 5
Part of https://github.com/owncloud/QA/issues/696
=> [tests-only]Update to latest .drone.star code and bump PHP phan to major version 5

tests/acceptance/features/bootstrap/GuestsContext.php, tests/acceptance/features/bootstrap/WebUIGuestsContext.php, tests/acceptance/features/bootstrap/bootstrap.php, tests/acceptance/features/lib/SetPasswordPage.php
Related https://github.com/owncloud/QA/issues/694
- add strict type checking on acceptace test code
**note** this PR was generated by a automated script
=> [Tests-Only] enforce strict type checking in acceptace tests code

lib/AppWhitelist.php
In order to make totp app work out of the box for guest users, we added twofactor_totp to the app whitelist. 
https://github.com/owncloud/twofactor_totp/issues/247
=> Add twofactor_totp to default whitelist

js/guests.js, lib/Controller/SettingsController.php, templates/settings/admin.php
fixes: https://github.com/owncloud/enterprise/issues/4990
=> allow setting share block domains in admin panel

templates/settings/admin.php
@pmaier1 as discussed in https://github.com/owncloud/guests/issues/498
=> improve block domains admin setting

lib/Controller/UsersController.php, lib/Mail.php, templates/mail/invite.php
=> feat: allow to send guest invites without shares

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Release 0.12.0

tests/acceptance/features/apiGuests/guests.feature, tests/acceptance/features/webUIGuests/guests.feature
Interspacing between two scenarios is made consistent as documented https://github.com/owncloud/docs-server/pull/697/files#diff-12a0f404a5bbbda65e50018a487cd725797106d670f4308b921d2081dc4b3516R1129-R1154:~:text=more%20relevant%20discussion.-,%3D%3D%3D%3D%20Inter%2Dscenario%20spacings,%2D%2D%2D%2D,-Commenting%20on%20lines
- Part of https://github.com/owncloud/QA/issues/769
- :robot:
=> [full-ci] [tests-only] Refactored inter scenarios space

.drone.star
This reverts commit 5caaba9cd036df4e8156b8f18aba156866889917.
Issue https://github.com/owncloud/QA/issues/746
=> [tests-only] [full-ci] Revert "Do not test with S3 and core latest 10.10"

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Merge back Release 0.12.1

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Release 0.12.2

tests/acceptance/config/behat.yml, tests/acceptance/features/apiGuests/guests.feature, tests/acceptance/features/bootstrap/GuestsContext.php
This PR adds test for removing `files_versions` from whitelist for guests app
Related to issue: https://github.com/owncloud/guests/issues/522
=> [tests-only][full-ci] test for removing files_versions from whilelist for guest app

package.json, tests/js/karma.config.js, yarn.lock
=> fix: use ChromeHeadless instead of PhantomJS

.drone.star, composer.json, composer.lock, lib/Controller/SettingsController.php, lib/Controller/UsersController.php, lib/Hooks.php, lib/Mail.php, lib/Settings/Admin.php, phpstan.neon, tests/acceptance/features/lib/GuestsPage.php, tests/acceptance/features/lib/SetPasswordPage.php, vendor-bin/behat/composer.json, vendor-bin/owncloud-codestyle/composer.json, vendor-bin/php_codesniffer/composer.json, vendor-bin/phpstan/composer.json
- update `.drone.star` code from activity app
- update tool dependencies
- update to coding-style 4.1
=> [tests-only] [full-ci] Update tool dependencies and drone CI code

yarn.lock
=> Bump karma-coverage from 2.2.0 to 2.2.1

.drone.star
- remove the use of `drone_token`
- adjust the use of the `cache_s3` tokens to use the names now available
Part of issue https://github.com/owncloud/QA/issues/818
=> [CI][full-ci]Update drone starklark file

lib/AppWhitelist.php
Make guest's core_whitlist consistent with 
/core/shipped.json -> alwaysEnabled
=> Update AppWhitelist.php add always enabled apps to core whitelist

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> Merge back release 0.12.3

lib/AppWhitelist.php, lib/Controller/SettingsController.php
=> fix: harden apis

CHANGELOG.md, appinfo/info.xml, sonar-project.properties
=> release: 0.12.4

package.json, yarn.lock
=> Bump karma from 6.4.2 to 6.4.3

lib/Mail.php
This PR fixes nightly failures caused by `Implicit nullable parameters` issue
Part of: https://github.com/owncloud/QA/issues/859
CI
=> test(refactor): fix nullable parameters error in nightly failure
