- settings/admin.php
I think this makes sense in the authentication section. In core we are renaming 'Authentication' to 'User Authentication'. Better than registering its whole own section.
> Move to authentication section instead of own section

- lib/mail.php
Prevents warnings in log
@IljaN please review
> Use user id instead of user object in mail status

- README.md
- appinfo/routes.php
- controller/settingscontroller.php
- js/guests.js
- lib/appwhitelist.php
* comma and core are moved to the backend and not visible in the settings any more https://github.com/owncloud/guests/issues/125
* accept enter key to save group and whitelist https://github.com/owncloud/guests/issues/112
* removed getWhitelist from settingscontroller and routes as it was not in use
> Whitelist: move "," and core to backend, have enter key working

- controller/settingscontroller.php
- js/guests.js
There never was a check against an empty group name, additionally moved success msg to backend.
(issue: https://github.com/owncloud/guests/issues/113)
> do not accept empty group names

- lib/hooks.php
- lib/mail.php
Removed email functionality in post_shared hook when guest user is already registered (as discussed in #84).
What was tested?
Do not send w/o admin settings _Allow users to send mail notification ..._:
* Share with a new guest user -> invite email is sent
* Share another file with this guest user -> no email is sent
Send with admin settings
* As an Admin in the Sharing Section check _Allow users to send mail notification for shared files to other users_
* Share with an existing guest user
* Check _notify by email_ in the ShareTab -> email is sent
> do not send share information after guest had registered

- js/guestshare.js
Only add guest entry if there is no matching user share in the list.
Detect if no results exist and adjust the UI accordingly when adding
guest entry.
Follow up of https://github.com/owncloud/guests/pull/149
> Fix guest autocomplete addition

- appinfo/app.php
- appinfo/routes.php
- controller/settingscontroller.php
- js/navigation.js
- lib/appwhitelist.php
- lib/groupbackend.php
Inspired by https://github.com/owncloud/guests/issues/163 we bring back basic frontend app whitelistening:
* remove non-whitelisted apps from navigation menu
* cosmetic removal of items in files view (side nav, buttons, tabs)
* block /dav/comments if not whitelisted
> Apply whitelist to frontend and comments URLs

- controller/registercontroller.php
1. enable password_policy app and set some policies (or any app that can validate a password or trigger an error when setting the password)
2. create guest
3. open mail link
4. type in an invalid / non-compliant password
5. type a compliant password
"Token is invalid" error, cannot try again to set a password without using browser back button.
Token is preserved and more attempts can be done.
@cortho please review
cc @pmaier1
> Preserve token when reshowing form after error

- tests/integration/config/behat.yml
To be able to use command line functions in core a variable was required in the config file. That has to be modified in all apps using the same code.
Coming from owncloud/core#29265
> Added required change coming from core

- js/guestshare.js
Now the creation of guest users is offered when there is the @ character and at least one unicode or ascii character before and after the @.
fixes #169
> slightly more exact email check

- controller/userscontroller.php
- js/guestshare.js
- tests/integration/guests_features/Guests.feature
Prevent creating users using an email that already exists on the
backend.
The frontend now discards the guest creation entry if there is at least
one exact match for the search terms, which could refer to the user id
or email address (the latter being handled by the autocomplete backend)
Fixes https://github.com/owncloud/guests/issues/167
Requires https://github.com/owncloud/core/pull/29223 from core to be able to detect exact user matches. Without this core PR the app will still work, but the "Guest" entry will be visible. Clicking it will however display an error message. I think this is acceptable for people still on 10.0.3.
> Detect existing email/user on frontend and backend

- .travis.yml
- appinfo/info.xml
and adjust Travis matrix to run PHP 5.6+ against ``core`` ``stable10`` and PHP 7.1+ against ``master``
> Bump core max version to 10.1

- tests/acceptance/features/bootstrap/GuestsContext.php
- tests/acceptance/guests_features/Guests.feature
to match with current core acceptance test code.
The code prior to this failed complaining about:
```
│
╳  user 'guest@example.com' was not created by this test run (Exception)
│
└─ @AfterScenario # GuestsContext::cleanupGuests()
```
because it was trying to use the core methods to cleanup users, but had not told core about them in the first place.
> Refactor guest user creation and cleanup

- tests/acceptance/guests_features/Guests.feature
These days, to get mailhog URL... set up in ``EmailContext`` you need to tag the scenario ``@mailhog``
This makes guests API acceptance tests pass again.
> Tag scenarios that need mailhog

- tests/acceptance/features/apiGuests/guests.feature
Test for #198 
Requires https://github.com/owncloud/core/pull/31596 to be merged
> Test for chunking upload 

- js/navigation.js
- tests/js/navigationSpec.js
This logic belongs to core instead.
Added some bonus unit tests for the whitelist
Fixes https://github.com/owncloud/guests/issues/220
> Don't remove navigation menu if only a single item is available

- tests/acceptance/config/behat.yml
- tests/acceptance/features/bootstrap/GuestsContext.php
and use methods from core ``FeatureContext`` instead.
Helps standardize the way tests are done, and move away from the core trait files being used all over the place.
> Remove use BasicStructure from local acceptance test context

- tests/acceptance/features/bootstrap/GuestsContext.php
``guests.feature:130`` started failing last night.
The email body coming back from mailhog has "soft line breaks" in it - "=\r\n" sequences.
The plain text email displays fine in the mailhog UI, and actually the format is a proper email thing:
https://en.wikipedia.org/wiki/Quoted-printable
https://groups.google.com/forum/#!topic/yesodweb/yyqM77CGVv8
And in recent guests CI that passed, I can see those sequences going around in mailhog:
https://drone.owncloud.com/owncloud/guests/187/22
```
Sun, 30 Sep 2018 23:37:51 +0000\r\nSubject: user0 shared =?utf-8?Q?=C2=BBtmp=C2=AB?= with you\r\nFrom: user0 via ownCloud <owncloud@foobar.com>\r\nTo: "guest@example.com" <guest@example.com>\r\nMIME-Version: 1.0\r\nContent-Type: multipart/alternative;\r\n …
```
> Fix guest email parsing

- tests/acceptance/features/bootstrap/GuestsContext.php
``getMailhogUrl`` changed to ``getLocalMailhogUrl`` in core when separating the concept of mailhog URL from the point of view of the server and the test runner.
> Adjust acceptance test method call getLocalMailhogUrl

- controller/userscontroller.php
Use EventDispatcherInterface instead of EventDispatcher
so that the events are listened and are not missed by
any apps.
Signed-off-by: Sujith H <sharidasan@owncloud.com>
> Use EventDispatcherInterface instead of EventDispatcher

- .drone.yml
- Makefile
- tests/acceptance/features/bootstrap/GuestsContext.php
1) Change drone.yml so that tests are run against a "full" ownCloud server rather than using the built-in PHP dev server. This makes the testing closer to real-life and also means that the server log output is not all mixed in the Behat test step output.
2) Have the "new standard" in drone that has an ``owncloud-log`` section which tails the log file.
3) Add drone jobs for some pgsql and Oracle, just so we cover those in case there is anything weird.
4) The guest registration URL parsing from the email was dependent too much on how the full URL starts off - running on a system with ownCloud installed somewhere below the server root, or that ends up with ``index.php`` in the URL path or... could break the parssing out of the email address and token. That is fixed in the 2nd commit.
> Rework drone acceptance tests like other apps

- appinfo/info.xml
- tests/acceptance/features/bootstrap/GuestsContext.php
during acceptance test guest registration process, so that the problem is easier to see.
Otherwise the acceptance test error is like:
```
And guest user "guest" has registered                                                                                                  # GuestsContext::guestUserRegisters()
Notice: Undefined offset: 0 in /var/www/owncloud/apps/guests/tests/acceptance/features/bootstrap/GuestsContext.php line 261
```
which is not helpful.
> Assert email found

- templates/form.password.php
Add user_autofocus to the parameter list to fix
the error thrown in the logs.
Signed-off-by: Sujith H <sharidasan@owncloud.com>
> [WIP] Remove user_autofocus expectation from paramters list

- appinfo/info.xml
This is for a later guests app release as the current one 0.7.0 should go out before marketplace is ready for the new max-version format.
> Set max version to 10

- tests/acceptance/features/bootstrap/bootstrap.php
use the `bootstrap.php` from core
needed for https://github.com/owncloud/password_policy/issues/175
combining tests from multiple apps would load files multiple times if we use the local `bootstrap.php` everywhere
:robot:
> user bootstrap.php of core acceptance tests

- tests/acceptance/features/bootstrap/GuestsContext.php
allow to use that Given step with a password
https://github.com/owncloud/password_policy/issues/175
more flexibility
> allow to use 'Given user has registered' step with password

- Makefile
...as they were moved under `lib`
Fixes #309
> Remove controller and settings directories from build

- lib/AppWhitelist.php
Bad UX, Pdf Viewer not enabled by default. Users get warnings when accessing pdf files via WebUI
1.) Install ownCloud
2.) Enable Guest app, zero config
3) Enable files_pdfviewer
4) Share pdf file with new guest user
5) Activate new guest user
6) open pdf file
> Add Pdf Viewer to default whitelist

- lib/GroupBackend.php
- tests/unit/GroupBackendTest.php
Don't call getUsersForUserValue in AllConfig if not necessary. All methods with a given user context should call getUserValue.
Closes https://github.com/owncloud/enterprise/issues/3242
The current GroupInterface is not performant
> Fix high DB load on inGroup() and getUsersGroups() calls

- tests/acceptance/features/apiGuests/guests.feature
- tests/acceptance/features/webUIGuests/guests.feature
that changed in core https://github.com/owncloud/core/pull/35438
> Adjust create user steps

- tests/acceptance/features/bootstrap/WebUIGuestsContext.php
- tests/acceptance/features/webUIGuests/guests.feature
core PR https://github.com/owncloud/core/pull/35397 changed the display of the various types of users in the webUI sharing dropdown list.
Adjust the test expectation here in the guests app.
https://github.com/owncloud/core/issues/35098
`guests` app acceptance tests started failing.
Make them great again.
CI
> Adjust expected sharing dialog box text

- js/guestshare.js
- tests/acceptance/features/bootstrap/WebUIGuestsContext.php
The recent enhancement of the webUI sharing dropdown list in core PR https://github.com/owncloud/core/pull/35397 now puts the user type (local, federated, guest etc) on a second line. The extra `(guest)` in brackets that the guest app is putting is no longer needed and just adds redundant data to the user experience.
Remove the `(guest)` in brackets from the sharing dropdown list.
https://github.com/owncloud/core/issues/35098
Make the guests sharing webUI behavior match the recent changes in the core PR https://github.com/owncloud/core/pull/35397
Observing local webUI test runs to see that the share dropdown no longer has the extra `(guest)` text.
> Adjust guest sharing dropdown text

- .drone.yml
This test guarantee that the ```guests``` app runs correctly against 10.2.1 tarball.
Core 10.2.1 is officially released, we we need guests app to run correctly against this latest release.
> guest app test against 10.2.1 tarball

- .drone.yml
This is the same problem as https://github.com/owncloud/core/issues/36002
Remove the scality test matrix for now.
(and put it back when the core issue is resolved)
> Remove scality obectstore drone tests for now

- .drone.yml
This reverts commit 1a03930fa282404111321d8919cb7d12492cc43c.
from PR #352 because scality S3 server is working now.
Issue https://github.com/owncloud/core/issues/36002
> Revert "Remove scality obectstore drone tests for now"

- js/guestshare.js
Guest share is a wrapper over ShareDialogView and ShareModel. 
However, while adding share, share API was used instead of the wrapped class - this can cause issues like https://github.com/owncloud/richdocuments/issues/285
> Use model addShare instead of share api while wrapping ShareDialogView

- .drone.starlark
- .drone.yml
Update to "latest" drone starlark app code:
1) support running all suites split into a number of parts (some apps run core tests like this)
2) put knowledge about the `ceph` and `scality` S3 backends into the code, to remove repetition of this knowledge in multiple app configs
3) added a `build()` pipeline (that was used by the testing app, and might be useful in future for other apps?)
> Update drone starlark with latest code 20191011

- tests/acceptance/features/apiGuests/guests.feature
- tests/acceptance/features/webUIGuests/guests.feature
Add acceptance test to assert that regular user can be created using same email as of guest user
> Acceptance test to assert regular user can be created using same email as of guest user

- tests/acceptance/features/apiGuests/guests.feature
- tests/acceptance/features/bootstrap/GuestsContext.php
- tests/acceptance/features/bootstrap/WebUIGuestsContext.php
Before adding new test scenarios for PR #384 , refactor the existing acceptance tests:
- improve scenario descriptions
- split `Given`  and `When` steps
- add better error messages to `Assert` checks
Local run of acceptance tests
> [Tests-Only] Refactor acceptance tests

- lib/Controller/UsersController.php
- tests/acceptance/features/apiGuests/guests.feature
- tests/acceptance/features/bootstrap/GuestsContext.php
- tests/acceptance/features/webUIGuests/guests.feature
Use `rawurldecode` instead of `urldecode` for allowing `+` in guests emails since `urldecode` decodes also `+` symbol to a space character.
- Requires https://github.com/owncloud/core/pull/36613
- Fixes https://github.com/owncloud/enterprise/issues/3712
- also fixes #332 (the test steps about changing password of a guest user work fine now, so they are enabled again, see the last commit)
Since `urldecode` decodes also `+` symbol to a space character it is not possible to create guest users having i.e. the following format `name+2@test.com`, which is a perfectly fine format.
Manually by sharing with guest users having the `name+2@test.com` format over the sharing dialogue.
Acceptance tests scenarios have been added - see 2nd commit.
> Use rawurldecode for allowing "+" in guests emails

- tests/acceptance/features/apiGuests/guests.feature
- tests/acceptance/features/bootstrap/GuestsContext.php
- tests/acceptance/features/bootstrap/WebUIGuestsContext.php
`username` of a `guest user` is set to `lower-cased email addr` during creation. So, `lower-cased` email should be used to share resource with guest user.
- fixes https://github.com/owncloud/guests/issues/395
share with guest users with emails containing upper-case letters
- :rabbit:
> [Tests-Only] API acceptance tests for guest users with uppercases in email

- vendor-bin/behat/composer.json
Backport #399 to `release-0.8.3` branch.
Due to upstream changes in Behat Mink dependencies, this is needed to get acceptance test CI working.
> [0.8.3] Pin behat/mink to 1.7.1 and update other acceptance test dependencies

- appinfo/info.xml
Because of 
- #384 allow `+` in guest usernames
- #393 bump handlebars 4.1.1 to 4.7.3 (which might not play nicely with core 10.3.2?)
See discussion around https://github.com/owncloud/guests/issues/400#issuecomment-599860752 to decide if we should actually do this.
> [0.8.3] Set core min-version to 10.4

- CHANGELOG.md
- appinfo/info.xml
Because min server version has been increased to 10.4, the next guests release has to be 0.9.0
Please merge back, then I'll create a new 0.9.0 branch
> Merge back Release 0.8.3

- tests/acceptance/features/bootstrap/GuestsContext.php
- tests/acceptance/features/bootstrap/WebUIGuestsContext.php
Due to the changes made by PR https://github.com/owncloud/core/pull/39927/files in function `addUserToCreatedUsersList` few tests were failing this PR fixes that
Fixes: https://github.com/owncloud/guests/issues/493
> [tests-only] [full-ci] Fix failing acceptance tests

- tests/acceptance/features/bootstrap/WebUIGuestsContext.php
- tests/acceptance/features/lib/GuestsPage.php
- tests/acceptance/features/webUIGuests/guests.feature
This PR adds UI tests for sharing settings guests bloackdomains
- Part of https://github.com/owncloud/guests/issues/496
- CI
- Locally
> Added UI test scenario for blocked domains from sharing with guests

- lib/Hooks.php
fixes https://github.com/owncloud/enterprise/issues/5193
we can hit exception as `{"reqId":"redacted","level":3,"time":"redacted","remoteAddr":"redacted","user":"--","app":"PHP","method":"GET","url":"\/core\/js\/oc.js?v=a56e4d21fce3a1c65e121c2dc61d270c","message":"Parameter 1 to OCA\\WOPI\\Hooks::extendJsConfig() expected to be a reference, value given at \/var\/www\/owncloud\/lib\/private\/legacy\/hook.php#103"}`
align with other apps like https://github.com/owncloud/core/blob/master/apps/files/lib/App.php#L46
> for legacy hooks do not hint type

- phpunit.xml
This PR moves unit tests into tests/unit folder. And also tidy up the `phpunit.xml` to make standard format for all oc-apps as much as possible.
- Part of https://github.com/owncloud/impersonate/issues/198
> [tests-only][full-ci]Tidy up the phpunit xml file for `guests` app

- .drone.star
`files_primary_s3` `master` now has the code for the Guzzle7 major version change. So we know that it does not work with core "latest" 10.10. So do not test that combination.
Part of https://github.com/owncloud/core/issues/39387
CI
> [tests-only] [full-ci] Do not test with S3 and core latest 10.10

- .drone.star
- lib/AppInfo/Application.php
Provide extended attributes when the event is emitted.
Signed-off-by: Sujith H <sharidasan@owncloud.com>
Rebase of #371 
#516 
Manually set the apps whitelist in guests to include and exclude each of
- customgroups
- systemtags
- comments
- files_versions
- files_texteditor
And check that the corresponding functionality in the classic webUI is not displayed for a guest user when the app is not whitelisted.
> Provide extended attributes when the event is emitted

- appinfo/info.xml
PR #518 uses `UserExtendedAttributesEvent` that is added in core 10.11.0. So the next 0.12.0 release of the guests app needs core min-version set to 10.11
#516 #520
> set core min-version 10.11 for extended-attributes

- .drone.star
- tests/acceptance/features/apiGuests/guests.feature
- tests/acceptance/features/bootstrap/GuestsContext.php
- tests/acceptance/features/webUIGuests/guests.feature
https://github.com/owncloud/core/pull/40442 changed the email server used in tests from mailhog to inbucket. It also changed the tag used in feature files from `@mailhog` to `@email`
So make the same change here in the guests app.
Issue https://github.com/owncloud/QA/issues/771
> [tests-only] [full-ci] Change mailhog test tag to email

- lib/AppWhitelist.php
If encryption is used in an installation then it really needs to be always in the whitelisted apps for a guest, otherwise a guest is going to have trouble saving a file.
Similarly if files_primary_s3 is used in an installation then it really needs to be always in the whitelisted apps for a guest, otherwise a guest is going to have trouble saving a file.
So I think that these should be always part of the "core" whitelisted apps. There is not functionality that can be sensibly/usefully enabled and disabled for a guest user in these apps.
CI
> Add encryption and files_primary_s3 to CORE_WHITELIST

- lib/AppWhitelist.php
Extend whitelists
- https://github.com/owncloud/core/issues/40441
- https://github.com/owncloud/enterprise/issues/5428
Extend whitelists to make enabled apps available for guest users. Some apps should not be removed from the default whitelist (which is editable by the admin) therefore they are now hard-coded in the core whitelist.
Manually by enabling such apps as admin and make sure functionalities provided by those apps are also available for guest users.
> Extend whitelists

- tests/acceptance/features/apiGuests/guests.feature
- tests/acceptance/features/bootstrap/GuestsContext.php
- tests/acceptance/features/webUIGuests/guests.feature
This PR adds test scenarios for the comments panel visibility when the `comments` app is whitelisted and `comments` app is removed from whitelist.
- Reltated to 
https://github.com/owncloud/guests/issues/523
- Locally
- CI
> [tests-only][[full-ci] Added webUI acceptance tests for comments panel visibility

- tests/acceptance/features/apiGuests/guests.feature
This PR adds the test for adding `files_versions` to the whitelist for guest user
Related to issue: https://github.com/owncloud/guests/issues/522
> [tests-only][full-ci] added test for adding files_versions to the whilelist for guest user

- tests/acceptance/features/webUIGuests/guests.feature
Added these webUI tests with usewhitelist apps enabled
```feature
Scenario Outline: check sidebar panel when when specific app is whitelisted
Examples:
| app            | panel    |
| comments       | comments |
| systemtags     | tags     |
| files_versions | versions |
Scenario: check deleted files sidebar when files_trashbin app is whitelisted
Scenario: check deleted files sidebar when files_trashbin app is whitelisted
```
Closes https://github.com/owncloud/guests/issues/523
Dependent on PR https://github.com/owncloud/core/pull/40675
> [tests-only][full-ci] Added tests to check details panel and trashbin sidebar nav

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiGuests/guests.feature
This PR adds test for adding `comments` app in whitelist for guest users
Related to issue: https://github.com/owncloud/guests/issues/522
> [tests-only][full-ci] added test for adding comments app in the whitelist for guest user

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiGuests/guests.feature
This PR adds test for adding `systemtags` app in whitelist for the guest user.
Related to issue: https://github.com/owncloud/guests/issues/522
> [tests-only][full-ci] added test for adding systemtags app in the whitelist for guest user

- tests/acceptance/features/apiGuests/guests.feature
This PR adds bug demonstration test for removing `systemtag` app from whilelist for guest users, so that guest user cannot add, remove or view tags of a resource.
Related to issue: https://github.com/owncloud/guests/issues/551
> [tests-only][full-ci]added bug demo test for removing systemtags app from whitelist for guest users

- tests/acceptance/config/behat.yml
- tests/acceptance/features/apiGuests/guests.feature
This PR adds test for bug demonstration for adding and removing `files_trashbin` from whilelist for guest user, to check if the guest user are able to delete the shared files and if the deleted files are available in the trashbin.
Related to issue: https://github.com/owncloud/guests/issues/553
> [tests-only][full-ci] bug demo test for removing files_trashbin app from whitelist for guest user

- tests/acceptance/features/bootstrap/GuestsContext.php
Previous function addUserToCreatedUsersList contains $userId
```
public function addUserToCreatedUsersList(
?string $user,
?string $password,
?string $displayName = null,
?string $email = null,
?string $userId = null,
bool $shouldExist = true
):
```
but current code does not contains the parameter `$userId`,
So removing it for the calling function in this PR.
https://github.com/owncloud/guests/issues/580
> [tests-only][full-ci]Fix guest creation in API step

- phpstan.neon
Fixes #585 
Now that Symfony5 is in core, phpstan understands the correct parameter order for EventDispatcherInterface::dispatch
The entry in ignoreErrors is no longer needed.
> [full-ci] Remove EventDispatcherInterface::dispatch from phpstan ignoreErrors

- .drone.star
- tests/acceptance/features/apiGuests/guests.feature
- tests/acceptance/features/webUIGuests/guests.feature
When the core system setting `share_folder` is used, guest users have a problem - see the issue link below.
The problem was fixed in core - see the PR link below.
This guests PR adds test coverage. A scenario is added that sets `share_folder` and then verifies that a guest user can use a folder that is shared with them.
The scenario fails when run with core code before https://github.com/owncloud/core/pull/40864
```
Feature: Guests
Background:                       # /home/phil/git/owncloud/core/apps-external/guests/tests/acceptance/features/apiGuests/guests.feature:4
Given using OCS API version "1" # FeatureContext::usingOcsApiVersion()
And using new dav path          # FeatureContext::usingOldOrNewDavPath()
@email @skipOnOcV10.11 @skipOnOcV10.12
Scenario: A guest user can upload files …
```
> [tests-only] Add test scenario to check that guests work when share_folder is used

- lib/AppInfo/Application.php
Respect the `usewhitelist` flag
https://github.com/owncloud/enterprise/issues/6312
We do not want to send any information to core about the whitelisted apps in case the `usewhitelist` flag is set to `false`, which means admin opted out the `Limit guest access to an app whitelist` checkbox
- oC 10.13.4 + twofactor_totp 0.8.1
- remove the guests app version which comes bundled in 10.13.4 and install 0.9.3 (we install this version as this was the last version where `twofactor_totp` was not yet included in the default whitelist, see https://github.com/owncloud/guests/pull/479, introduced in 0.10.0)
- as admin opt-out the `Limit guest access to an app whitelist` checkbox
- login as guest, TOTP section is presented in the settings/personal?sectionid=security section --> all good
- now update …
> Fix: respect the usewhitelist flag

- lib/AppInfo/Application.php
- lib/Mail.php
Respect default_language for guests invitation
https://github.com/owncloud/enterprise/issues/6322
Currently, the `default_language` config.php option is wrongly not considered when generating templates for guests invitation. This has the consequence that the language of the user creating the guest is rather used, which may not be the same as the one used by the guest (especially true in case of guest users).
Note: the `sendGuestPlainInviteMail` method needed also to be adjusted as this is what is being used when creating a guest directly from custom groups --> https://github.com/owncloud/customgroups/blob/master/lib/Service/GuestIntegrationHelper.php#L124
Set `default_language` in config.php and observe this language is now used for guests templates.
> fix: respect default_language for guests invitation
